### ISSUE TITLE
Можно ли получить данные профиля?

### ISSUE THREAD

**Issue by mrcodewin** [oleghalin/Dota2Ladder_bot#2]
Добрый день. А можно ли использовать Вашего бота в качестве инструмента для получения информации которая указана в профиле?

Например человек выбрал в качестве информации: дату первого матча и кол-во похвал. 

Можно ли получить эту информацию?

**Comment by oleghalin** [comment]
requestPlayerMatchHistory(account_id, [options], [callback]) или так requestMatchDetails(match_id, [callback])

**Comment by mrcodewin** [comment]
А если мне нужно получить просто по id?  без всяких лобии и прочего. Просто бот, который получит информацию указанную в профиле. Сложно переделать?

**Comment by oleghalin** [comment]
profileData (account_id, profileData)

**Comment by mrcodewin** [comment]
Что нужно оставить из того что есть в вашем боте?

**Comment by oleghalin** [comment]
Бот не тяжелый, можно не удалять лишнее

**Comment by kprodinfo** [comment]
Ладно, попробую разобраться, просто никогда не работал с node

**Comment by kprodinfo** [comment]
Можете привести пример функции которая получит данные:?

**Comment by kprodinfo** [comment]
Поставил на сервер. Но почему то не хочет подключатся к базе данных. Не могли бы подсказать причину. Вот ответ: 
![image](https://cloud.githubusercontent.com/assets/20172275/18034211/1bcdca86-6d61-11e6-85f1-ccfe213bca30.png)

**Comment by kprodinfo** [comment]
Поставил на сервер, запустил, всё работает. Но не могу адаптировать под свою нужду. Подскажите пожалуйста. Как мне всё таки вытащить информацию из панели любого игрока? Пожалуйста помогите

**Comment by oleghalin** [comment]
Что конкретно не получается то?
