### ISSUE TITLE
Still works?

### ISSUE THREAD

**Issue by gbrlstr** [oleghalin/Dota2Ladder_bot#3]
I start the project but nothing happens.

**Comment by oleghalin** [comment]
@XxStR abandoned

**Comment by gbrlstr** [comment]
@oleghalin  
That sad :/
Anyway, I'm updating thank you very much.

**Comment by oleghalin** [comment]
@XxStR check Arcana repo

**Comment by gbrlstr** [comment]
@oleghalin 
many things have changed from your code to the current one Arcana.
I had a good success. least in kicking the player. :(

**Comment by oleghalin** [comment]
@XxStR If you want I can try to help you.
You can share your code here or to t.me/KhalinOleg

**Comment by gbrlstr** [comment]
@oleghalin  Thanks.
[Project](https://github.com/XxStR/AcademyDota2)

**Comment by gbrlstr** [comment]
@oleghalin Hi, did you get a view on the project?
